[general]
live_config_reload = true
import = ["~/personal/dotfiles/alacritty/rose-pine.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Off"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 22.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

# https://github.com/Avi-D-coder/FiraCode-italic
[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

# https://github.com/Avi-D-coder/FiraCode-italic
[font.italic]
family = "Fira Code"
style = "Regular Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

# [[keyboard.bindings]]
# action = "SpawnNewInstance"
# key = "Return"
# mods = "Control"

[window]
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.85

[window.dimensions]
columns = 155
lines = 70
