---
- name: "[{{ role_name }}] Install Python UV ({{ ansible_distribution }})"
  ansible.builtin.command: which uv
  register: uv_installed
  ignore_errors: true
  changed_when: false

- name: "[{{ role_name }}] Install Python UV ({{ ansible_distribution }})"
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -LsSf https://astral.sh/uv/install.sh | sh
  when: uv_installed.rc != 0
