require "main"

-- vim.api.nvim_set_hl(0, "StatusLine", { link = "NONE" })

-- vim.pack.add({
-- 	"https://github.com/folke/lazydev.nvim",
-- 	{
-- 		src = "https://github.com/hrsh7th/nvim-cmp",
-- 		opts = {
-- 			function(_, opts)
-- 				opts.sources = opts.sources or {}
-- 				table.insert(opts.sources, {
-- 					name = "lazydev",
-- 					group_index = 0,
-- 				})
-- 			end
-- 		}
-- 	},
-- 	{
--     src = "https://github.com/saghen/blink.cmp",
--     opts = {
--       sources = {
--         -- add lazydev to your completion providers
--         default = { "lazydev", "lsp", "path", "snippets", "buffer" },
--         providers = {
--           lazydev = {
--             name = "LazyDev",
--             module = "lazydev.integrations.blink",
--             -- make lazydev completions top priority (see `:h blink.cmp`)
--             score_offset = 100,
--           },
--         },
--       },
--     },
-- 	}
-- })
